### ISSUE TITLE
Missing class XeCryptRc4EcbKey in xcp_dumper.py

### ISSUE THREAD

**Issue by NicknineTheEagle** [GoobyCorp/Xbox_360_Crypto#1]
```
This will OVERWRITE and DELETE the original XCP file, press "ENTER" if you want to continue...
Decrypting XCP file...
Decrypting CAB header...
Traceback (most recent call last):
  File "D:\Sources\Xbox_360_Crypto\xcp_dumper.py", line 205, in <module>
    main()
  File "D:\Sources\Xbox_360_Crypto\xcp_dumper.py", line 108, in main
    init_crypto_at(0x60)
  File "D:\Sources\Xbox_360_Crypto\xcp_dumper.py", line 103, in init_crypto_at
    XeCryptRc4EcbKey(XeCryptHmacSha(args.key, bytes(rc4_sha_struct.cksm)))
NameError: name 'XeCryptRc4EcbKey' is not defined
```
Seems like it's supposed to be in XeCrypt.py but it's not there.

**Comment by GoobyCorp** [comment]
This should be fixed in https://github.com/GoobyCorp/Xbox_360_Crypto/commit/86046b35a287f4eefa1d3b48e446129b0ea153cb, just tell me if you have any issues.

**Comment by NicknineTheEagle** [comment]
What about the key used to decrypt XCP? Is it same for all packages like on PS3 or is it per game? How would one go along dumping it?

**Comment by GoobyCorp** [comment]
It's per-package, you have to have a module loaded with hooks to NetDll_recv and XeCryptRc4 to dump the key.

On August 15, 2021 9:44:28 AM EDT, NicknineTheEagle ***@***.***> wrote:
>What's the key used to decrypt XCPs? Is it same for all packages like on PS3 or is it per game? How would one go along dumping it?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GoobyCorp/Xbox_360_Crypto/issues/1#issuecomment-899052597
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NicknineTheEagle** [comment]
Is there no way to obtain the key from a PC if I own the game in question?

**Comment by InternalLoss** [comment]
Alternatively, does a module already exist that can dump these keys, and if so is there code/a compiled build for users to run?

**Comment by NicknineTheEagle** [comment]
@GoobyCorp Could you elaborate on that module and key fetching?
