### ISSUE TITLE
verify_keys.py missing?

### ISSUE THREAD

**Issue by JohnVeness** [GoobyCorp/Xbox_360_Crypto#2]
The readme mentions (and tries to link to) a verify_keys.py file, but the file appears to be missing?

**Comment by GoobyCorp** [comment]
It was replaced by keystore.py it will load the keys and verify them. I'll update the readme when I get the chance.

On April 11, 2023 11:38:33 AM EDT, John Veness ***@***.***> wrote:
>The readme mentions (and tries to link to) a verify_keys.py file, but the file appears to be missing?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GoobyCorp/Xbox_360_Crypto/issues/2
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
