### ISSUE TITLE
[Q] xb360 saves decryption tool

### ISSUE THREAD

**Issue by eadmaster** [GoobyCorp/Xbox_360_Crypto#3]
is there a tool that can be used to decrypt xb360 saves?

My aim is to load some xb360 saves on game ports for a different system (PS3 and PC)

**Comment by GoobyCorp** [comment]
Horizon is what you're looking for

**Comment by eadmaster** [comment]
i had a better luck with [this old version of Moodio](https://modio.en.uptodown.com/windows) +  [this resigner](https://www.youtube.com/watch?v=almzeYpi2do)
